//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.42000。
// 
#pragma warning disable 1591

namespace MCCard.MCCard_EC_Service {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MCCard_ECSoap", Namespace="http://tempuri.org/")]
    public partial class MCCard_EC : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback validateCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryBonusOperationCompleted;
        
        private System.Threading.SendOrPostCallback queryTxnOperationCompleted;
        
        private System.Threading.SendOrPostCallback lostOperationCompleted;
        
        private System.Threading.SendOrPostCallback balance_transferOperationCompleted;
        
        private System.Threading.SendOrPostCallback verify_wifiOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public MCCard_EC() {
            this.Url = global::MCCard.Properties.Settings.Default.MCCard_MCCard_EC_Service_MCCard_EC;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event validateCardCompletedEventHandler validateCardCompleted;
        
        /// <remarks/>
        public event queryCardCompletedEventHandler queryCardCompleted;
        
        /// <remarks/>
        public event queryBonusCompletedEventHandler queryBonusCompleted;
        
        /// <remarks/>
        public event queryTxnCompletedEventHandler queryTxnCompleted;
        
        /// <remarks/>
        public event lostCompletedEventHandler lostCompleted;
        
        /// <remarks/>
        public event balance_transferCompletedEventHandler balance_transferCompleted;
        
        /// <remarks/>
        public event verify_wifiCompletedEventHandler verify_wifiCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/validateCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string validateCard(string jsondata) {
            object[] results = this.Invoke("validateCard", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void validateCardAsync(string jsondata) {
            this.validateCardAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void validateCardAsync(string jsondata, object userState) {
            if ((this.validateCardOperationCompleted == null)) {
                this.validateCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnvalidateCardOperationCompleted);
            }
            this.InvokeAsync("validateCard", new object[] {
                        jsondata}, this.validateCardOperationCompleted, userState);
        }
        
        private void OnvalidateCardOperationCompleted(object arg) {
            if ((this.validateCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.validateCardCompleted(this, new validateCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryCard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryCard(string jsondata) {
            object[] results = this.Invoke("queryCard", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryCardAsync(string jsondata) {
            this.queryCardAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void queryCardAsync(string jsondata, object userState) {
            if ((this.queryCardOperationCompleted == null)) {
                this.queryCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryCardOperationCompleted);
            }
            this.InvokeAsync("queryCard", new object[] {
                        jsondata}, this.queryCardOperationCompleted, userState);
        }
        
        private void OnqueryCardOperationCompleted(object arg) {
            if ((this.queryCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryCardCompleted(this, new queryCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryBonus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryBonus(string jsondata) {
            object[] results = this.Invoke("queryBonus", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryBonusAsync(string jsondata) {
            this.queryBonusAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void queryBonusAsync(string jsondata, object userState) {
            if ((this.queryBonusOperationCompleted == null)) {
                this.queryBonusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryBonusOperationCompleted);
            }
            this.InvokeAsync("queryBonus", new object[] {
                        jsondata}, this.queryBonusOperationCompleted, userState);
        }
        
        private void OnqueryBonusOperationCompleted(object arg) {
            if ((this.queryBonusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryBonusCompleted(this, new queryBonusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/queryTxn", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string queryTxn(string jsondata) {
            object[] results = this.Invoke("queryTxn", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void queryTxnAsync(string jsondata) {
            this.queryTxnAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void queryTxnAsync(string jsondata, object userState) {
            if ((this.queryTxnOperationCompleted == null)) {
                this.queryTxnOperationCompleted = new System.Threading.SendOrPostCallback(this.OnqueryTxnOperationCompleted);
            }
            this.InvokeAsync("queryTxn", new object[] {
                        jsondata}, this.queryTxnOperationCompleted, userState);
        }
        
        private void OnqueryTxnOperationCompleted(object arg) {
            if ((this.queryTxnCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.queryTxnCompleted(this, new queryTxnCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/lost", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string lost(string jsondata) {
            object[] results = this.Invoke("lost", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void lostAsync(string jsondata) {
            this.lostAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void lostAsync(string jsondata, object userState) {
            if ((this.lostOperationCompleted == null)) {
                this.lostOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlostOperationCompleted);
            }
            this.InvokeAsync("lost", new object[] {
                        jsondata}, this.lostOperationCompleted, userState);
        }
        
        private void OnlostOperationCompleted(object arg) {
            if ((this.lostCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.lostCompleted(this, new lostCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/balance_transfer", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string balance_transfer(string jsondata) {
            object[] results = this.Invoke("balance_transfer", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void balance_transferAsync(string jsondata) {
            this.balance_transferAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void balance_transferAsync(string jsondata, object userState) {
            if ((this.balance_transferOperationCompleted == null)) {
                this.balance_transferOperationCompleted = new System.Threading.SendOrPostCallback(this.Onbalance_transferOperationCompleted);
            }
            this.InvokeAsync("balance_transfer", new object[] {
                        jsondata}, this.balance_transferOperationCompleted, userState);
        }
        
        private void Onbalance_transferOperationCompleted(object arg) {
            if ((this.balance_transferCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.balance_transferCompleted(this, new balance_transferCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/verify_wifi", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string verify_wifi(string jsondata) {
            object[] results = this.Invoke("verify_wifi", new object[] {
                        jsondata});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void verify_wifiAsync(string jsondata) {
            this.verify_wifiAsync(jsondata, null);
        }
        
        /// <remarks/>
        public void verify_wifiAsync(string jsondata, object userState) {
            if ((this.verify_wifiOperationCompleted == null)) {
                this.verify_wifiOperationCompleted = new System.Threading.SendOrPostCallback(this.Onverify_wifiOperationCompleted);
            }
            this.InvokeAsync("verify_wifi", new object[] {
                        jsondata}, this.verify_wifiOperationCompleted, userState);
        }
        
        private void Onverify_wifiOperationCompleted(object arg) {
            if ((this.verify_wifiCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verify_wifiCompleted(this, new verify_wifiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void validateCardCompletedEventHandler(object sender, validateCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class validateCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal validateCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void queryCardCompletedEventHandler(object sender, queryCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void queryBonusCompletedEventHandler(object sender, queryBonusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryBonusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryBonusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void queryTxnCompletedEventHandler(object sender, queryTxnCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class queryTxnCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal queryTxnCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void lostCompletedEventHandler(object sender, lostCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class lostCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal lostCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void balance_transferCompletedEventHandler(object sender, balance_transferCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class balance_transferCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal balance_transferCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    public delegate void verify_wifiCompletedEventHandler(object sender, verify_wifiCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1586.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verify_wifiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verify_wifiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591